### ISSUE TITLE
Crashes at launch on Linux

### ISSUE THREAD

**Issue by CorruptComputer** [unitystation/stationhub#168]
Downloaded the latest version from the website at the time of writing, currently as `lin930.zip`.

Tried to launch the game, and it crashed with this as the stack trace:
```
[user@host UnityStation]$ ./StationHub 
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Guid.TryParseExactD(System.ReadOnlySpan`1<Char>, GuidResult ByRef)
   at System.Guid.TryParseGuid(System.ReadOnlySpan`1<Char>, GuidResult ByRef)
   at System.Guid..ctor(System.String)
   at Avalonia.MicroCom.MicroComRuntime..cctor()
   at Avalonia.MicroCom.MicroComRuntime.RegisterVTable(System.Type, IntPtr)
   at Avalonia.Native.Interop.Impl.__MicroComIAvnApplicationEventsVTable.__MicroComModuleInit()
   at <Module>..cctor()
   at UnitystationLauncher.Program.BuildAvaloniaApp()
   at UnitystationLauncher.Program.Main(System.String[])
Aborted (core dumped)
```

I am using Fedora 37, it says something about an ICU package missing. I searched the Fedora repos for anything that mentioned that and didn't find much. Unless it is referring to this package, in which case it is already installed so I'm not sure why its broken: https://packages.fedoraproject.org/pkgs/icu/

Perhaps a list of required dependencies to run the game should be added somewhere? I looked in the GitHub README and on the Wiki linked in the main UnityStation repo, no mentions of any required dependencies on either of those.

**Comment by CorruptComputer** [comment]
I also almost posted the bug report over on the main UnityStation repo, had no idea that this was being downloaded from a separate repo. The website doesn't make that clear at all, the GitHub link next to the download button takes you that repo instead of here.

**Comment by corp-0** [comment]
inside the application directory, modify ``StationHub.runtimeconfig.json`` so it looks like this

```
{
  "runtimeOptions": {
    "additionalProbingPaths": [
      "Lib"
    ],
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "3.1.21"
      }
    ],
    "tfm": "netcoreapp3.1",
    "configProperties": {
      "System.Globalization.Invariant": true
    }
  }
}
``` 

alternatively, try the most recent version which we haven't released yet and let me know how it goes. Go here https://github.com/unitystation/stationhub/actions/runs/3818354761 and scroll all the way to the bottom.

**Comment by CorruptComputer** [comment]
Both worked for me, adding that to the existing release lets it run fine and the unreleased version with no changes works fine too. Thanks!
